language: python
python:
        - "2.7"
install:
        - pip install -r requirements.txt
script:
        - coverage run -m unittest discover --start-directory tests --top-level-directory . --verbose
        - coverage xml -o coverage.xml
